# Generated by Django 5.0.4 on 2024-04-29 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_saga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('duracao', models.IntegerField()),
                ('imagem', models.CharField(max_length=200)),
                ('data_publicacao', models.DateTimeField()),
                ('genre', models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='movies.genre')),
                ('saga', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movies.saga')),
            ],
        ),
    ]
