# Generated by Django 5.0.4 on 2024-04-29 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_publicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscolhaFilme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessao', models.DateTimeField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.evento')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filme')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.utilizador')),
                ('voto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.escolhafilme')),
            ],
        ),
    ]
