# Generated by Django 5.0.4 on 2024-04-29 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_escolhafilme_voto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaFilmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('V', 'Vistos'), ('F', 'Futuros')], max_length=1)),
                ('grupo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movies.grupo')),
                ('utilizador', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movies.utilizador')),
            ],
        ),
    ]
