# Generated by Django 5.0.4 on 2024-04-29 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_elementolista'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilizadorGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrador', models.BooleanField(default=False)),
                ('convite_por_aceitar', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.grupo')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.utilizador')),
            ],
        ),
    ]
