# Generated by Django 5.0.4 on 2024-04-29 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_utilizadorgrupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilizadorCinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.cinema')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.utilizador')),
            ],
        ),
    ]
