# Generated by Django 5.0.4 on 2024-04-29 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_utilizadorcinema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='saga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.saga'),
        ),
        migrations.AlterField(
            model_name='listafilmes',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.grupo'),
        ),
        migrations.AlterField(
            model_name='listafilmes',
            name='utilizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.utilizador'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='cinema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.cinema'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='filme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.filme'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.grupo'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.publicacao'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='timestamp_fim',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='timestamp_inicio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
