# Generated by Django 5.0.4 on 2024-05-06 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_mensagem_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='utilizador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.utilizador'),
            preserve_default=False,
        ),
    ]
