# Generated by Django 5.0.4 on 2024-05-07 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_publicacao_utilizador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='imagem',
            field=models.CharField(default='NO_USER_IMAGE', max_length=200),
        ),
        migrations.AlterField(
            model_name='filme',
            name='imagem',
            field=models.CharField(default='NO_MOVIE_IMAGE', max_length=200),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='imagem',
            field=models.CharField(default='NO_GROUP_IMAGE', max_length=200),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='data_adesao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilizadorgrupo',
            name='date_joined',
            field=models.DateTimeField(null=True),
        ),
    ]
