# Generated by Django 5.0.3 on 2024-05-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_utilizador_imagem_alter_filme_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='nome',
            field=models.CharField(default='giveName', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filme',
            name='imagem',
            field=models.CharField(default='NO_MOVIE_IMAGE.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='imagem',
            field=models.CharField(default='NO_GROUP_IMAGE.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='imagem',
            field=models.CharField(default='NO_USER_IMAGE.png', max_length=200),
        ),
    ]
