# Generated by Django 5.0.4 on 2024-05-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_utilizador_imagem_alter_filme_imagem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilizadorgrupo',
            old_name='convite_por_aceitar',
            new_name='convite_por_aceitar_grupo',
        ),
        migrations.AddField(
            model_name='grupo',
            name='publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilizadorgrupo',
            name='convite_por_aceitar_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='imagem',
            field=models.CharField(default='NO_MOVIE_IMAGE.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='imagem',
            field=models.CharField(default='NO_GROUP_IMAGE.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='imagem',
            field=models.CharField(default='NO_USER_IMAGE.png', max_length=200),
        ),
    ]
