# Generated by Django 5.0.3 on 2024-05-11 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_cinema_nome_alter_filme_imagem_alter_grupo_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacaoCinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.cinema')),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.publicacao')),
            ],
        ),
        migrations.CreateModel(
            name='PublicacaoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.grupo')),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.publicacao')),
            ],
        ),
    ]
