# Generated by Django 5.0.4 on 2024-05-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_rename_convite_por_aceitar_utilizadorgrupo_convite_por_aceitar_grupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='imagem',
            field=models.CharField(default='movies/images/NO_MOVIE_IMAGE.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='imagem',
            field=models.CharField(default='movies/images/NO_GROUP_IMAGE.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='imagem',
            field=models.CharField(default='movies/images/NO_USER_IMAGE.png', max_length=200),
        ),
    ]
