# Generated by Django 5.0.4 on 2024-05-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_filme_imagem_alter_grupo_imagem_and_more'),
        ('movies', '0015_publicacaocinema_publicacaogrupo'),
    ]

    operations = [
    ]
