# Generated by Django 5.0.6 on 2024-05-12 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_rename_convite_por_aceitar_utilizadorgrupo_convite_por_aceitar_grupo_and_more'),
        ('movies', '0015_publicacaocinema_publicacaogrupo'),
    ]

    operations = [
    ]
