# Generated by Django 5.0.6 on 2024-05-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_merge_20240512_0152'),
        ('movies', '0016_merge_20240512_1547'),
    ]

    operations = [
    ]
